### ISSUE TITLE
Getting E61040001

### ISSUE THREAD

**Issue by tanvir0604** [sanmai/gmopg#5]
Hi,I have implemented the payment system according to your instructions and using real shop id (not test shop).I am getting E61040001 error when trying to use my cc.Can you tell me what else do I need to do?This is error code means "no full card no allowed".Should I enter only a part of the card no?

**Comment by sanmai** [comment]
You need to contact GMO PG with a request of a permission to use a full card number for payments. I guess they'll ask for some sort of PCI DSS certification. As I understand C-VT SAQ Validation Type does not require vulnerability scanning, but GMO PG may have a different opinion on that matter. Obviously you must be using HTTPS on your site.

See #4 for an extended discussion, and the final comment there. Please understand these things are beyond my control.

**Comment by dmitrymalys** [comment]
Hi, we have same error in the live version, we using ssl. We have called GMO and they told as to include toke witch you get true they js lib that is in the documentation 'トークン決済サービス仕様書_1_21.pdf' .  Can we send token using your lib and how we can do it? Also can we acquire token using your lib?

**Comment by sanmai** [comment]
I'm pretty sure you can, but this library currently cannot work with their JS library. Since then you need to contact GMO PG with a request of a permission to use a full card number for payments.

Pull requests are very much welcome though. Again, I refer you to #4 for an extended discussion.

**Comment by dmitrymalys** [comment]
I have solve the problem for my project (laravel 5.5), let me explain the flow. I didn't  do the PR since, if Author wants he can add changes. 

You can find errors codes [here](https://faq.gmo-pg.com//service/Detail.aspx?id=e366332514f6561726b4942754e3349782b636e307476666970684567583543524b75534b425257567959513d&kindId=-7&category=0&categoryNot=0&word=E61040001&listNo=2&cntPerPage=15&page=1&totalCount=3&type=0&search=7&sort=99&order=2&attributeSearch=) and see what they mean. 

Translation of E61040001 error: "[Affiliated store setting error]
You can not enter a card number.
The current contract does not allow payment processing with a card number.
Please carry out token correspondence instead of linking card numbers as they are."

Basically instead of card details you need to send the token, to get the token you will have to send the card details from your frontend using they js script. You can find it in the documentation.

Insert script in to your page: `<script src="https://static.mul-pay.jp/ext/js/token.js"></script>`,
After that insert this code: 
```
<script type="text/javascript">
        function execPurchase(response) {
            if (response.resultCode != "000") {
                window.alert("購入処理中にエラーが発生しました");
            } else {

                document.getElementById("token").value = response.tokenObject.token;
                document.getElementById("purchaseForm").submit();
            }
        }
        function doPurchase() {
            var cardno, expire, securitycode, holdername;
            var cardno = document.getElementById("CardNumber").value.replace(/\s/g, '');
            var expire = document.getElementById("expireYear").value + document.getElementById("expireMonth").value;
            var securitycode = document.getElementById("securityCode").value;
            var holdername = document.getElementById("holderName").value;
            var tokennumber = document.getElementById("tokenNumber").value;

            Multipayment.init(shop_id);
            Multipayment.getToken({
                cardno : cardno,
                expire : expire,
                securitycode : securitycode,
                holdername : holdername,
                tokennumber : tokennumber
            }, execPurchase);
        }
    </script>
```

What are we doing here is basically, sending card details  to the GMO and they send back the token, then we input token in to the hidden input and submitting form. 

Now we need to publish the package to make changes inside it:

In laravel you can do this: 

1. Create a folder Packages in your project directory.
2. Put there all the package files.
3. In your composer.json add GMO class to the "autoload" in "psr-4":
```
"autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/",
            "GMO\\": "packages/sanmai/gmopg/src"
        }
    }
```
Now change the package code. 

4. In `ImmediatePayment.php` add  `public $token;`
5.  In same file add token to the array of values to be passed: 
```
public function execute()
    {
        foreach (['paymentId', 'amount', 'cardYear', 'cardMonth', 'cardCode', 'token'] as $requiredVar) {
            if (empty($this->$requiredVar)) {
                throw new Exception("Missing $requiredVar");
            }
        }
```
6. In the same function at line #130 where is `// setup card number and such` comment the `setCardNumber` and new function `setToken`:
```
        // setup card number and such
        // $this->execTran->setCardNumber($this->cardNumber);
        $this->execTran->setCardExpiryYearMonth($this->cardYear, $this->cardMonth);
        $this->execTran->setCardSecurityCode($this->cardCode);
        $this->execTran->setToken($this->token);
        $this->execTranResponse = $this->execTran->dispatch();  
```
7. At the `/packages/sanmai/gmopg/src/GMO/API/Call/ExecTran.php` add `public $Token;` and create function `setToken`:

```
    public function setToken($token)
    {
        $this->Token = $token;

        return $this;
    }
```

8. In the same file add token to the `dispatch` function and remove CardNo(IMPORTANT): 

```
    public function dispatch()
    {
        $this->withRequired($this->OrderID, $this->AccessID, $this->AccessPass);
        $this->withRequired($this->Expire, $this->SecurityCode, $this->Token);

        // needed by the GMO PG for whatever reasons there are
        $this->HttpAccept = $_SERVER['HTTP_ACCEPT'];
        $this->HttpUserAgent = $_SERVER['HTTP_USER_AGENT'];

        return parent::dispatch();
    } 
```
Again, this how it works in my case. Hope it will help some one.

**Comment by sanmai** [comment]
Are you sure you still need required to pass `Expire` and `SecurityCode`? Will it work without them?

I'd rather see a solid PR to accept, but this will work too.

**Comment by sanmai** [comment]
Fixed in the most recent release.

```php
$payment = new \GMO\ImmediatePayment();
$payment->paymentId = 123; // Unique ID for every payment; see above
$payment->amount = 1000;
// Card details are unnecessary in this case
$payment->token = $_POST['token']; // token from the JavaScript API

if (!$payment->execute()) {
    // ... as usual
}
```

**Comment by sanmai** [comment]
> 1. Create a folder Packages in your project directory.
> 2. Put there all the package files.
> 3. In your composer.json add GMO class to the "autoload" in "psr-4":

You really should be using Composer's magic to install and update packages. Putting stuff you can get from a package as a plain copy to some directory is beyond bad. Don't do this please.

**Comment by dmitrymalys** [comment]
@sanmai Im not sure about `Expire` and `SecurityCode`, if you try to send card number with token it will return error. Yes and you right about copying vendor files.  Better to fork or in case of Laravel use `artisan vendor:publish`. Thank you for the update.
